version: '3'

services:

  pgsql:
    image: postgres
    container_name: dashboard_pgsql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  dash:
    build:
      context: .
      dockerfile: Dockerfile.dash
    container_name: dashboard_dash
    command: python app.py
    volumes:
      - .:/src
    ports:
      - "5000:8080"
    depends_on:
      - pgsql
